### ISSUE TITLE
Add to README

### ISSUE THREAD

**Issue by steve-fields** [ucsb-cs56-projects/cs56-games-alva#2]
I've left a bare readme for this project. Add screenshots, objectives, class descriptions etc.

**Comment by steve-fields** [comment]
F17 OK (100 pts)

**Comment by pconrad** [comment]
The README.md is definitely improved.    The gifs are there.  I'm going to leave it up to Steven to make the final determination as to whether what he had in mind for the 100 pts is done.

But it looks like some good improvements were made.

**Comment by steve-fields** [comment]
F17 CLOSED
