### ISSUE TITLE
Don't allow robot to jump when tiles are above it

### ISSUE THREAD

**Issue by ok-wang** [ucsb-cs56-projects/cs56-games-alva#20]
You can make the robot object jump even when there is a tile above of it. Please try to figure out how to make sure the robot object doesn't even attempt to jump when below a tile

**Comment by steve-fields** [comment]
F17 OK (100pts)

**Comment by steve-fields** [comment]
Hint: The animation works by checking whether up is being held, might be better to look at y velocity.

**Comment by steve-fields** [comment]
W18 OK (100pts)

**Comment by steve-fields** [comment]
W18 CLOSED
