### ISSUE TITLE
Move Ant to Maven or Gradle

### ISSUE THREAD

**Issue by steve-fields** [ucsb-cs56-projects/cs56-games-alva#25]
We are starting to move away from ant and towards maven or gradle. Both of these provide a wider toolset for our needs.

**Comment by steve-fields** [comment]
W18 OK (50 pts)

**Comment by RayMuhlenkamp** [comment]
I have somewhat addressed this issue on the gradleRefactor branch of my forked repo. Essentially, I have done is initialized the gradle files and the gradle wrapper within the repo, and then imported the prior ant build.xml file into the gradle build file, so we can use the old ant tasks until the time we choose to completely switch. This gives us more flexibility in development, as we can use the added benefits of gradle when we find use for them, but in the meantime we can continue to utilize the ant workflow that already works. If this fills the criteria of the issue, let me know, but if not, let me know what else you would like me to do.

**Comment by RayMuhlenkamp** [comment]
Actually, a quick update on this, I added java and application dependencies to the build.gradle file, and it can now build and run independently of the prior ant workflow. I am keeping in the ant workflow for now though.

**Comment by RayMuhlenkamp** [comment]
Double update, I am running into a lot of issues with gradle installations. Is there anyway we can get gradle properly installed on CSIL machines?

**Comment by RayMuhlenkamp** [comment]
Triple Update: I think I have got the gradle wrapper installed properly in the repo itself that it shouldn't matter if gradle itself isn't installed. So I think I have actually fufilled the issue at this point. Not sure

**Comment by steve-fields** [comment]
W18 CLOSED
